### PR TITLE
use internal labeled pipeline, fixes #15

### LINKED ISSUE #15: "post" transform
Bankai adds some transforms that run after your package.json transforms, but sometimes you want to do things to your html at the end. Maybe edit some bankai-inserted nodes (eg https://github.com/choojs/bankai/issues/315) or [minifying the server-rendered document](https://github.com/goto-bus-stop/html-minify-stream).

We could implement this quite easily using a [labeled-stream-splicer](https://npmjs.com/package/labeled-stream-splicer), with labels for package.json transforms, transforms added through the API, and transforms that should run at the end.

Two ideas for how configuration could work for that:

* A separate `postTransform` key

```json
{
  "documentify": {
    "transform": [ "./run-first" ],
    "postTransform": [ "./run-last" ]
  }
}
```
```js
Documentify()
  .transform('./run-first')
  .postTransform('./run-last')
```

* An `order` option on transforms to specify the label. eg, with labels `pre`, `mid`, `post`:

```js
{
  "documentify": {
    "transform": [
      "./run-first", // default order: "pre"
      ["./run-last", { "order": "post" }],
    ]
  }
}
```
```js
Documentify()
  .transform('./run-first') // default order: "mid"
  .transform('./run-last', { order: 'post' })
```

### PR DESCRIPTION
**Pull request by goto-bus-stop**
as discussed in #15 . labels 'start'/'main'/'end'—not a big fan of 'main', but couldn't think of something better :)

something's not working yet, transform order is funny w/ this patch…opening this up tho so i'll remember or someone else can try to figure it out if they want to.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Digging this!

**Comment by goto-bus-stop** [comment]
Oh crap I completely forgot about this 😂

**Comment by yoshuawuyts** [comment]
Ahahaha - looks like it's conflicting now tho :P

**Comment by goto-bus-stop** [comment]
passing :tada:

**Review by yoshuawuyts — APPROVED** [review]

**Comment by goto-bus-stop** [comment]
:package: 3.2.0

**Pull request merged**
